// This file is released under the 3-clause BSD license. See COPYING-BSD.
// Generated by builder.sce : Please, do not edit this file
// cleaner.sce
// ------------------------------------------------------
curdir = pwd();
cleaner_path = get_file_path('cleaner.sce');
chdir(cleaner_path);
// ------------------------------------------------------
if fileinfo('loader.sce') <> [] then
  mdelete('loader.sce');
end
// ------------------------------------------------------
if fileinfo('libinherit.so') <> [] then
  mdelete('libinherit.so');
end
// ------------------------------------------------------
if fileinfo('libinherit.cpp') <> [] then
  mdelete('libinherit.cpp');
end
// ------------------------------------------------------
if fileinfo('libinherit.hxx') <> [] then
  mdelete('libinherit.hxx');
end
// ------------------------------------------------------
if fileinfo('libinherit.h') <> [] then
  mdelete('libinherit.h');
end
// ------------------------------------------------------
chdir(curdir);
// ------------------------------------------------------
